[deploy]
startCommand = "python manage.py migrate && gunicorn capstone.wsgi:application --bind 0.0.0.0:$PORT"
healthcheckPath = "/"
healthcheckTimeout = 50
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5

[build]
builder = "NIXPACKS"