# Generated by Django 5.2 on 2025-05-19 09:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budgetallocation',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='budgetproposal',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='budgetproposal',
            name='rejected_by',
        ),
        migrations.RemoveField(
            model_name='budgetproposal',
            name='submitted_by',
        ),
        migrations.AddField(
            model_name='budgetallocation',
            name='created_by_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='budgetproposal',
            name='approved_by_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='budgetproposal',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='budgetproposal',
            name='rejected_by_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='budgetproposal',
            name='submitted_by_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='budgetproposal',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
