# Generated by Django 5.2 on 2025-05-19 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_budgetallocation_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetproposal',
            name='document',
            field=models.FileField(blank=True, help_text='Optional file attached with the proposal, such as an Excel budget sheet.', null=True, upload_to='budget_proposals/documents/'),
        ),
    ]
