# Generated by Django 5.2 on 2025-05-21 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_budgetproposal_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposalhistory',
            name='action_by',
        ),
        migrations.AddField(
            model_name='proposalhistory',
            name='action_by_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
