# Generated by Django 5.2 on 2025-05-28 04:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_proposalhistory_action_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='accomplished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='accomplishment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='budgetallocation',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='budgetallocation',
            name='funding_source',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='funded_allocations', to='core.account'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='budgetproposal',
            name='status',
            field=models.CharField(choices=[('SUBMITTED', 'Submitted'), ('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='SUBMITTED', max_length=20),
        ),
    ]
