# Generated by Django 5.2 on 2025-05-30 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_account_accomplished_account_accomplishment_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budgetallocation',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='budgetallocation',
            name='funding_source',
        ),
        migrations.AlterField(
            model_name='budgetproposal',
            name='status',
            field=models.CharField(choices=[('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='APPROVED', max_length=20),
        ),
    ]
