# Generated by Django 5.2 on 2025-05-30 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_budgetallocation_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetallocation',
            name='category',
            field=models.ForeignKey(default=1, help_text='The expense category this allocation is intended for', on_delete=django.db.models.deletion.PROTECT, related_name='budget_allocations', to='core.expensecategory'),
            preserve_default=False,
        ),
    ]
