# Generated by Django 5.2 on 2025-06-05 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_budgetallocation_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetproposal',
            name='performance_notes',
            field=models.TextField(blank=True, help_text='Narrative description of the period of performance.'),
        ),
    ]
