# Generated by Django 5.2 on 2025-06-06 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_budgetproposal_performance_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetproposal',
            name='status',
            field=models.CharField(choices=[('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='SUBMITTED', max_length=20),
        ),
    ]
